server:
  port: 48081
spring:
  application:
    name: RateLimitCalleeService
  cloud:
    loadbalancer:
      configurations: default
    polaris:
      address: grpc://9.135.224.139:8091
      discovery:
        namespace: default