server:
  port: 48081
spring:
  application:
    name: RateLimitCalleeService
  cloud:
    loadbalancer:
      configurations: default
    polaris:
      address: grpc://127.0.0.1:8091
      discovery:
        namespace: default